### ISSUE TITLE
sign-up page

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [AlexanderTahtadjian/saas-website#2]
@muxlowc
I'm not sure why but for some reason my sign up page isn't showing up and saying that it doesn't exist, event though my code says it does. I'm not exactly sure how to fix that.

**Comment by muxlowc** [comment]
@AlexanderTahtadjian  you have a typo on your html file :)

Yours says "sing-up.html"  - so just rename it, and it should fix it!

**Comment by AlexanderTahtadjian** [comment]
@muxlowc 
ok
