### ISSUE TITLE
Join page buttons

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [AlexanderTahtadjian/saas-website#3]
@muxlowc
I'm not exactly sure how to make both the sign up and log in buttons the same size as the sign up with Facebook and sign up with gmail buttons?

**Comment by muxlowc** [comment]
@AlexanderTahtadjian 
on your btn-4 (join with facebook) - take out the max-width, and add "width: 100%"
and same thing with btn-5

Hope this helps!

**Comment by muxlowc** [comment]
@AlexanderTahtadjian oops i think I misread your question:

You could make the width of the btn-4 and btn-5, width: 50% which would make them the same width as the buttons above it

**Comment by AlexanderTahtadjian** [comment]
@muxlowc 
ok thanks
